### ISSUE TITLE
make bin doesn't work

### ISSUE THREAD

**Issue by jannone** [plainspooky/flappybird4msx#1]
The README states that there is a build mode for BIN files invoked by `make bin`

However, this is the result of running it:
```
flappybird4msx$ make bin
make: *** No rule to make target `bin'.  Stop.
```

Running on a Mac OS X Catalina (10.15.4)

**Comment by plainspooky** [comment]
Oh my, I've removed the old fashioned BIN generation method to use the same way as Nohzdyve and did forget to update. :-)
